In [36]:
import numpy as np
import pandas as pd


**Q1** Generate random sample from the finite population using
        (i) SRSWR
        (ii) SRSWOR
        (iii) Unequal probabilities for population elements.

####  SRSWR

In [37]:
n=10
np.random.choice(range(10),n,replace=True)

array([8, 0, 9, 7, 6, 2, 3, 4, 2, 8])

#### SRSWOR

In [38]:
n=10
np.random.choice(range(10),n,replace=False)

array([8, 0, 4, 3, 1, 9, 5, 7, 6, 2])

#### Unequal probabilities for population elements.

In [39]:
n=10
np.random.choice(range(4),n,replace=True,p=[0.1,0.3,0.5,0.1])

array([2, 2, 2, 3, 2, 3, 2, 2, 2, 2])

**Q2** Generate random sample of size 10,000 from 𝑃𝑜𝑖𝑠𝑠𝑜𝑛(𝜆 = 3). Treat this generated sample 
data as characteristic values of study variables of the population of the size 10,000. 
Now, draw 5 random samples of size 100 each from this population using SRSWOR, obtain 
estimate of population mean based on each sample data by using sample mean as an 
estimator for population mean. Also find the amount of sampling error from your 
estimates

#### Random sample from Poisson Disribution (Population)

In [40]:
N=10000
lam=3
population=np.random.poisson(lam,N)
population_mean=np.mean(population)

   #### Sample From Population

In [41]:
n=100
k=5
sample_means=[]
for i in range(k):
    sample=np.random.choice(population,n,replace=False)
    sample_mean=np.mean(sample)
    sample_means.append(sample_mean)
    i+=1
    

#### Samples mean and Population mean

In [42]:
print("sample_means=",sample_means)
print("population_mean=",np.mean(population))

sample_means= [2.71, 3.12, 2.67, 3.08, 3.09]
population_mean= 3.0075


#### Sampling Errors

In [43]:
sampling_errors=population_mean-sample_means
print("sampling_errors=",sampling_errors)

sampling_errors= [ 0.2975 -0.1125  0.3375 -0.0725 -0.0825]


**Q3 Draw 10,000 samples of size 25 from Normal (100,${3^2}$) and study the sampling distribution of following statistics for n=5,10**
 $i) Y_{bar}$
  $ii)  S_y=\frac{1}{n-1}\sum_{i=1}^n(Y_r-{Ybar})^2$
  $iii) Y_{(1)}=min(Y_1,Y_2,....Y_n)$
 $ iv) Y_{(n)}=max(Y_1,Y_2,....Y_n)$
  $v) R=Y_{(n)}-Y_{(1)}$
        

In [44]:
n=25
n1=5
n2=10
k=10000
mu=1000
sd=3
samples_mean=[]
samples_var=[]
samples_min=[]
samples_max=[]
samples_range=[]
for i in range(k):
    population=np.random.normal(mu,sd,n)
    sample=np.random.choice(population,n1,replace=False)
    sample_mean=np.mean(sample)
    sample_var=np.var(sample)
    sample_min=np.min(sample)
    sample_max=np.max(sample)
    sample_range=sample_max-sample_min   
    samples_mean.append(sample_mean)
    samples_var.append(sample_var)
    samples_max.append(sample_max)
    samples_min.append(sample_min)
    samples_range.append(sample_range)
    i+=1

*Similarly for n=10* 

$i) Y_{bar}$

In [45]:
print("samples_mean=",samples_mean)


samples_mean= [1001.4826515486254, 998.1693162352219, 999.6987267570715, 1002.1166049402593, 1000.5385680786452, 998.6897678721056, 1000.4859059948424, 998.3797092174842, 1002.1567744956455, 999.5537017781908, 999.6127623236544, 999.8150420057488, 999.7319487277122, 1000.717455029376, 999.832628726379, 1000.3221147878558, 1000.8184721502736, 998.7524104970337, 1000.5899317570575, 999.1945929108333, 998.9225593698986, 1001.8820424627295, 1000.6032213341798, 1000.0349109877334, 1000.8816613168201, 999.1297057316254, 1000.9607111503414, 999.8159479867663, 998.344726242424, 1000.7066023534042, 998.5537343228922, 999.9701898990512, 1000.6535270995106, 998.4100120632371, 1000.128161991675, 1000.4700895112294, 1000.1083824313666, 999.492412558797, 1002.2997303478174, 1001.9623780770183, 1001.5883588494111, 999.6515431430271, 997.7281703184783, 1001.257306706511, 1000.4291969649628, 1001.0878152693322, 997.9299236346731, 1001.7499019542593, 1000.3412160718419, 999.5959876466393, 998.7224676444

$ii)  S_y=\frac{1}{n-1}\sum_{i=1}^n(Y_r-{Ybar})^2$

In [46]:
print("samples_variance=",samples_var)

samples_variance= [2.9903521611133925, 4.118356160879051, 11.199719204834285, 19.592278281988804, 6.893740243220033, 4.796913764350448, 14.084069991085684, 1.8962139153209523, 8.183639198943709, 13.026031027686518, 2.2950648581289035, 10.811111060910596, 8.755319717977986, 4.974180522715041, 3.9344248058275353, 13.177531879202462, 2.484046292303896, 1.1094246065551823, 5.213141446256632, 5.608727517833467, 0.9252863458863212, 7.087380107046482, 3.7310956982989048, 5.6650588321846325, 4.274752937897217, 1.6169505117374308, 1.9499465325915466, 6.0182560947687875, 1.0284927919786948, 3.6960008489613445, 10.498028354083129, 5.174050424561411, 1.75445968873556, 1.3486885118823237, 2.7511800168224334, 5.049876790146038, 6.5987534065837945, 6.379091868032482, 7.384892019260337, 5.135550878420648, 3.3790424974684137, 4.918939014532565, 8.790124290147535, 8.782905025834761, 7.394460692707869, 1.9365915912445058, 9.449278161497174, 18.809518655123206, 7.764293135522978, 1.285945142958458, 6.5680

$iii) Y_{(1)}=min(Y_1,Y_2,....Y_n)$

In [47]:
print("samples_minimum=",samples_min)

samples_minimum= [999.3396830775895, 994.881695901614, 994.857836240363, 994.1032678325097, 995.9055189426753, 995.6622875498642, 995.7992600789282, 996.2188701517007, 999.2049575521097, 994.9238753171668, 998.2504950988592, 997.0611543833868, 994.9901951467484, 997.2970433901324, 997.1366707701771, 993.754318284486, 998.3306438074471, 997.3045620114549, 997.6117431869409, 995.760760980308, 997.6557779244318, 999.3576837576318, 997.5321554057836, 997.1163010371747, 998.3432889795765, 997.4332252797662, 999.3430554841054, 997.48464811153, 996.4502725297182, 998.5637552142937, 993.1645786540948, 995.476310979413, 998.6364077921072, 996.1974482664258, 997.8493457050502, 996.4397589958586, 997.0478852617624, 995.6564835033142, 998.9702959765789, 999.439335066048, 999.5155745500481, 997.3053468654039, 994.1040569858783, 997.5608524408021, 995.6169417588985, 999.0636695327736, 993.3188143857489, 997.1769524919231, 997.3648301435699, 998.3753984063126, 994.1466889282013, 994.8979527602783, 99

$ iv) Y_{(n)}=max(Y_1,Y_2,....Y_n)$

In [48]:
print("samples_maximum=",samples_max)


samples_maximum= [1004.2748897423827, 1001.2267327534878, 1003.2456277747515, 1006.4969686730327, 1003.2905567457807, 1000.9197244975044, 1006.9776023453701, 1000.2604965837879, 1007.126499355058, 1005.927740220341, 1001.9782322058156, 1006.0218764841608, 1004.1705983453171, 1004.3284668163764, 1001.7635312508648, 1004.3693487006783, 1002.7360693685839, 1000.120562467561, 1003.6579925093395, 1003.1200451099036, 1000.3210062200906, 1005.5557976277848, 1003.1307010785163, 1004.3011641123373, 1004.5567927173793, 1000.6478530641057, 1003.3828719248979, 1004.4025269960003, 999.2980903164153, 1003.8566901091616, 1002.804043324308, 1001.6897300541086, 1002.4324278678486, 999.338063506182, 1002.2179471541853, 1003.1308101656408, 1004.723808769291, 1003.1496251098581, 1006.9219660117965, 1006.0575693333699, 1004.4803957960105, 1003.4051834160183, 1002.0049280699517, 1006.6213270726813, 1003.8220837618284, 1003.1051745847058, 1002.69302274169, 1009.4866934536666, 1005.0862156505236, 1001.6894569

 $v) R=Y_{(n)}-Y_{(1)}$

In [49]:
print("samples_range=",samples_range)

samples_range= [4.935206664793213, 6.345036851873829, 8.387791534388498, 12.393700840523024, 7.385037803105433, 5.257436947640144, 11.17834226644186, 4.0416264320872415, 7.921541802948241, 11.00386490317419, 3.727737106956397, 8.960722100773978, 9.180403198568683, 7.031423426243919, 4.6268604806876965, 10.615030416192326, 4.405425561136781, 2.816000456106053, 6.04624932239858, 7.359284129595608, 2.6652282956587214, 6.198113870153065, 5.598545672732712, 7.184863075162639, 6.213503737802739, 3.2146277843394273, 4.039816440792492, 6.917878884470383, 2.847817786697078, 5.292934894867926, 9.639464670213215, 6.213419074695594, 3.796020075741353, 3.1406152397562437, 4.368601449135099, 6.691051169782213, 7.675923507528637, 7.4931416065438725, 7.951670035217603, 6.6182342673218955, 4.964821245962412, 6.099836550614441, 7.900871084073401, 9.060474631879174, 8.205142002929847, 4.041505051932177, 9.374208355941164, 12.3097409617435, 7.721385506953766, 3.3140585844527095, 7.629394915574949, 8.16396